/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.yageek.tulipindicators;

class Bindings {
  static { System.loadLibrary("tulipjni"); }
  private native void loadIndicators();
  native BindingsResponse call_indicator(String name, double[] inputs,
                                         double[] options);
  Bindings() { loadIndicators(); }

  static class Response {
    final double[] values;
    final int beginIndex;

    Response(int beginIndex, double[] values) {
      this.values = values;
      this.beginIndex = beginIndex;
    }
  }
}
