/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.yageek.tulipindicators;

public class Bindings {

  static { System.loadLibrary("tulipjni"); }
  private native void loadIndicators();
  native Response call_indicator(String name, double[] inputs,
                                 double[] options);
  private Bindings() { loadIndicators(); }

  private static Bindings INSTANCE = new Bindings();

  static final Bindings shared() { return INSTANCE; }

  public static class Response {
    final double[] values;
    final int beginIndex;

    Response(int beginIndex, double[] values) {
      this.values = values;
      this.beginIndex = beginIndex;
    }
  }
}
