/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_yageek_tulipindicators_Tulip */

#ifndef _Included_net_yageek_tulipindicators_Tulip
#define _Included_net_yageek_tulipindicators_Tulip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_yageek_tulipindicators_Tulip
 * Method:    loadIndicators
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_yageek_tulipindicators_Tulip_loadIndicators
  (JNIEnv *, jobject);

/*
 * Class:     net_yageek_tulipindicators_Tulip
 * Method:    call_indicator
 * Signature: (Ljava/lang/String;[D[D)Lnet/yageek/tulipindicators/TulipRawResponse;
 */
JNIEXPORT jobject JNICALL Java_net_yageek_tulipindicators_Tulip_call_1indicator
  (JNIEnv *, jobject, jstring, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
