/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_yageek_tulipindicators_Bindings */

#ifndef _Included_net_yageek_tulipindicators_Bindings
#define _Included_net_yageek_tulipindicators_Bindings
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     net_yageek_tulipindicators_Bindings
 * Method:    loadIndicators
 * Signature: ()V
 */
  JNIEXPORT void JNICALL Java_net_yageek_tulipindicators_Bindings_loadIndicators(JNIEnv *, jobject);

  /*
 * Class:     net_yageek_tulipindicators_Bindings
 * Method:    callIndicator
 * Signature: (Ljava/lang/String;[D[D)Lnet/yageek/tulipindicators/Bindings/Response;
 */
  JNIEXPORT jobject JNICALL Java_net_yageek_tulipindicators_Bindings_callIndicator(JNIEnv *, jobject, jstring, jdoubleArray, jdoubleArray);

  /*
 * Class:     net_yageek_tulipindicators_Bindings
 * Method:    getIndicatorInfo
 * Signature: (Ljava/lang/String;)Lnet/yageek/tulipindicators/Bindings/IndicatorInfo;
 */
  JNIEXPORT jobject JNICALL Java_net_yageek_tulipindicators_Bindings_getIndicatorInfo(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
