/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.yageek.tulipindicators;

import static org.junit.Assert.*;

import org.junit.Test;

public class TulipTest {
  @Test
  public void testJNIBindings() {

    double[] inputs = new double[] {-1.0, -2.0, -3.0};
    double[] expected = new double[] {1.0, 2.0, 3.0};

    Bindings.Response resp =
        Bindings.shared().call_indicator("abs", inputs, null);

    assertNotNull(resp);

    assertEquals(0, resp.beginIndex);

    assertEquals(expected.length, resp.values.length);

    double EPS = 1e-4;
    for (int i = 0; i < resp.values.length; i++) {
      assertTrue(Math.abs(resp.values[i] - expected[i]) < EPS);
    }
  }
}
