/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.yageek.tulipindicators;

import static org.junit.Assert.*;

import org.junit.Test;

public class TulipTest {
  @Test
  public void testSomeLibraryMethod() {
    Tulip classUnderTest = new Tulip();
    assertTrue("someLibraryMethod should return 'true'",
               classUnderTest.someLibraryMethod());
  }
}
